djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path

from . import views
app_name = 'users'
urlpatterns = [
    path('', views.index, name='user_index'),
    path('create_user', views.createUser, name='user_add'),
]

users/models.py
from django.db import models


class User(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    username = models.CharField(max_length=30)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)

    def to_dict(self):
        return {
            "id": self.id,
            "first_name": self.first_name,
            "last_name": self.last_name,
            "username": self.username,
            "address": self.address,
            "phone": self.phone}

users/views.py
from django.http import HttpResponse
from django.template import loader
from django.http import JsonResponse

from .models import User


def index(request):
    users = User.objects.order_by('id')
    template = loader.get_template('users/index.html')
    context = {
        'users': users,
    }
    return HttpResponse(template.render(context, request))


def createUser(request):
    awaitingKeys = ['first_name', 'last_name', 'address', 'phone', 'username','csrfmiddlewaretoken']
    testKeys = True

    for k, v in request.POST.items():
        if k not in awaitingKeys:
            testKeys = False
    if testKeys == False:
        return JsonResponse({'message': 'form is invalid'}, status=401)
    else:
        for k in awaitingKeys:
            if (len(request.POST[k]) == 0):
                return JsonResponse({'message': k + ' is empty'}, status=401)

        if User.objects.filter(username=request.POST['username']).exists():
            return JsonResponse({'message': 'username already exist'}, status=401)
        u = User(first_name=request.POST['first_name'],
                 last_name=request.POST['last_name'],
                 address=request.POST['address'],
                 phone=request.POST['phone'],
                 username=request.POST['username'],
                 )
        u.save()
        return JsonResponse({'user': u.to_dict()}, status=200)

users/templates/users/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <link rel="stylesheet" href="{% static 'users/css/bootstrap.min.css' %}" >
    <title>Users</title>

  </head>
  <body >
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="">Users app</a>
      </div>
    </nav>
    <div class=" p-5 row mt-1">
        <div class="col-md-4">

            <form>
                {% csrf_token %}
          <h1 > Add new user</h1>
          <p style="font-size: 10px"> item with star are required</p>
          <div class="mb-3">
            <label for="first_name" class="form-label">First Name *</label>
            <input maxlength="30" type="text" class="form-control" id="first_name" name="first_name" aria-describedby="first_nameHelp" required>

          </div>

          <div class="mb-3">
            <label for="last_name" class="form-label">Last Name *</label>
            <input maxlength="30" type="text" class="form-control" id="last_name" name="last_name" aria-describedby="last_nameHelp" required>

          </div>

          <div class="mb-3">
            <label for="address" class="form-label">Address *</label>
            <input type="text" class="form-control" id="address" name="address" aria-describedby="addressHelp" required>

          </div>

          <div class="mb-3">
            <label for="phone" class="form-label">Phone number *</label>
            <input type="number" class="form-control" id="phone" name="phone" aria-describedby="phoneHelp" required>

          </div>

          <div class="mb-3">
            <label for="username" class="form-label">Username *</label>
            <input type="text" class="form-control" id="username" name="username" aria-describedby="usernameHelp" required>

          </div>
          <p class="mb-3 alert-danger" id="error">

          </p>

          <button id="submit-btn" type="submit" class="btn btn-primary">Submit</button><img style="display: none" id="loading" width="50px" height="50px" src="{% static 'users/images/loader.svg' %}">
    </form>

        </div>
        <div class="col-md-8">
                <table class="table table-responsive">
                <thead>
                <th>username</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Address</th>
                <th>Phone Number</th>
                </thead>
                <tbody id="table-body">
                {% for user in users %}
                    <tr>
                    <td>{{ user.username }}</td>
                <td>{{ user.first_name }}</td>
                <td>{{ user.last_name }}</td>
                <td>{{ user.address }}</td>
                <td>{{ user.phone }}</td>
                    </tr>

                {% endfor %}

                </tbody>
                </table>


       </div>

    </div>





  <script src="{% static 'users/js/jquery-3.5.1.js' %}"></script>
  <script src="{% static 'users/js/jquery.tmpl.js' %}"></script>
  <script src="{% static 'users/js/popper.min.js' %}"></script>
  <script src="{% static 'users/js/bootstrap.min.js' %}"></script>
    <script>
        let myTemplate = '<tr><td>${username}</td><td>${first_name}</td><td>${last_name}</td><td>${address}</td><td>${phone}</td></tr>';
        $.template("myTemplate", myTemplate);
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
    return cookieValue;
    }
        const csrftoken = getCookie('csrftoken');
        const suggestUsername = () =>{
             $("#username").val($("#first_name").val() + '-' + $("#last_name").val());
        };

        $("#first_name").on('change',function (e){
            if($("#last_name").val().length>0){
               suggestUsername();
            }
        });

        $("#last_name").on('change',function (e){
            if($("#first_name").val().length>0){
               suggestUsername();
            }
        });


    $("#submit-btn").on('click',function (e){
      e.preventDefault();
       $("#error").html("");
      $("#submit-btn").attr("disabled", true);
      $("#loading").show();
      const form = document.querySelector('form');
      const dataToSend = Object.fromEntries(new FormData(form).entries());

      $.ajax({
        headers: {'X-CSRFToken': csrftoken},
        url: '{% url 'users:user_add' %}',
        type: 'POST',
        dataType: 'json',
        data: dataToSend ,
        success: function(data){
          console.log(data.user);
         $.tmpl("myTemplate", data.user).appendTo("#table-body");

          $("#loading").hide();
          $("#submit-btn").attr("disabled", false);
        },
        error :function (data) {
            $("#error").html(data.responseJSON.message);

          $("#submit-btn").attr("disabled", false);
          $("#loading").hide();


        }
      });


    });


  </script>
  </body>
</html>